### ISSUE TITLE
【错误】报错故障--TypeError: 'NoneType' object is not subscriptableTypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by OrdinaryJoys** [Chenyme/Chenyme-AAMT#39]
You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.1.117:8501

- 本次任务目录：C:/Users/G1763/Downloads/AAVT_0.8.4_full (1)/AAVT_0.8.4_full/project/cache/2024-07-05 11-52-57
2024-07-05 11:53:03.043 WARNING streamlit:
  Warning: to view a Streamlit app on a browser, use Streamlit in a file and
  run it with the following command:

    streamlit run [FILE_NAME] [ARGUMENTS]
2024-07-05 11:53:03.053 WARNING streamlit.runtime.state.session_state_proxy: Session state does not function when running a script without `streamlit run`
2024-07-05 11:53:06.299 WARNING streamlit:
  Warning: to view a Streamlit app on a browser, use Streamlit in a file and
  run it with the following command:

    streamlit run [FILE_NAME] [ARGUMENTS]
2024-07-05 11:53:06.308 WARNING streamlit.runtime.state.session_state_proxy: Session state does not function when running a script without `streamlit run`

*** Faster Whisper 本地模型加载模式 ***

- 运行模型：C:/Users/G1763/Downloads/AAVT_0.8.4_full (1)/AAVT_0.8.4_full/model/large-v3
- 运行方式：cuda
- VAD辅助：True
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\G1763\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\G1763\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\G1763\Downloads\AAVT_0.8.4_full (1)\AAVT_0.8.4_full\project\utils\utils2.py", line 143, in faster_whisper_result
    segments, _ = model.transcribe(file_path,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\G1763\Downloads\AAVT_0.8.4_full (1)\AAVT_0.8.4_full\env\Lib\site-packages\faster_whisper\transcribe.py", line 397, in transcribe
    encoder_output = self.encode(segment)
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\G1763\Downloads\AAVT_0.8.4_full (1)\AAVT_0.8.4_full\env\Lib\site-packages\faster_whisper\transcribe.py", line 838, in encode
    return self.model.encode(features, to_cpu=to_cpu)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid input features shape: expected an input with shape (1, 128, 3000), but got an input with shape (1, 80, 3000) instead
***正在生成SRT字幕文件***

2024-07-05 11:53:10.179 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\G1763\Downloads\AAVT_0.8.4_full (1)\AAVT_0.8.4_full\env\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\G1763\Downloads\AAVT_0.8.4_full (1)\AAVT_0.8.4_full\Chenyme-AAVT.py", line 42, in <module>
    media()
  File "C:\Users\G1763\Downloads\AAVT_0.8.4_full (1)\AAVT_0.8.4_full\project\media.py", line 701, in media
    srt_content = generate_srt_from_result(result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\G1763\Downloads\AAVT_0.8.4_full (1)\AAVT_0.8.4_full\project\utils\utils2.py", line 525, in generate_srt_from_result
    segments = result['segments']
               ~~~~~~^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
![Snipaste_2024-07-05_11-55-12](https://github.com/Chenyme/Chenyme-AAVT/assets/90075145/5502286a-a84f-49a8-a1d8-d3a28ee2fdea)

**Comment by chenyme** [comment]
您好！请查看 [此文档](https://zwho5v3j233.feishu.cn/wiki/C7akw4w44iFEEPky8fScjqFWnbf?from=from_copylink) 的 `Part 3 运行识别` 中的 `第一条`
