### ISSUE TITLE
【错误】KeyError: 'st.session_state has no key "w_model_option"

### ISSUE THREAD

**Issue by jeffreyrobeson** [Chenyme/Chenyme-AAMT#4]
Traceback (most recent call last):
  File "C:\Users\Administrator\pinokio\bin\miniconda\lib\site-packages\streamlit\runtime\state\session_state_proxy.py", line 119, in __getattr__
    return self[key]
  File "C:\Users\Administrator\pinokio\bin\miniconda\lib\site-packages\streamlit\runtime\state\session_state_proxy.py", line 90, in __getitem__
    return get_session_state()[key]
  File "C:\Users\Administrator\pinokio\bin\miniconda\lib\site-packages\streamlit\runtime\state\safe_session_state.py", line 91, in __getitem__
    return self._state[key]
  File "C:\Users\Administrator\pinokio\bin\miniconda\lib\site-packages\streamlit\runtime\state\session_state.py", line 400, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "w_model_option". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\pinokio\bin\miniconda\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "E:\software\Chenyme_AAVT_0.5.1\Chenyme_AAVT_0.5.1\pages\📽️视频(Video).py", line 59, in <modul e>
    result = get_whisper_result(uploaded_file, output_file, device, st.session_state.w_model_option,
  File "C:\Users\Administrator\pinokio\bin\miniconda\lib\site-packages\streamlit\runtime\state\session_state_proxy.py", line 121, in __getattr__
    raise AttributeError(_missing_attr_error_message(key))
AttributeError: st.session_state has no attribute "w_model_option". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization

**Comment by chenyme** [comment]
您好！非常感谢你的反馈。
我已在近一次的测试中发现该报错，预计下个版本会修复此问题。

在此之前，你可以重新打开AAVT-HomePage页面，以获取缓存，再打开其他页面。

**Comment by chenyme** [comment]
你好，最新版本中已解决这个问题，感谢你的指出！
