### ISSUE TITLE
【求助】已经删除libiomp5md.dll仍报错TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by denpa773** [Chenyme/Chenyme-AAMT#44]
- 本次任务目录：D:/idm/AAVT_0.8.4_small/project/cache/2024-07-25 03-16-03
2024-07-25 03:16:07.513 WARNING streamlit:
  Warning: to view a Streamlit app on a browser, use Streamlit in a file and
  run it with the following command:

    streamlit run [FILE_NAME] [ARGUMENTS]
2024-07-25 03:16:07.522 WARNING streamlit.runtime.state.session_state_proxy: Session state does not function when running a script without `streamlit run`
2024-07-25 03:16:11.833 WARNING streamlit:
  Warning: to view a Streamlit app on a browser, use Streamlit in a file and
  run it with the following command:

    streamlit run [FILE_NAME] [ARGUMENTS]
2024-07-25 03:16:11.843 WARNING streamlit.runtime.state.session_state_proxy: Session state does not function when running a script without `streamlit run`

*** Faster Whisper 本地模型加载模式 ***

- 运行模型：D:/idm/AAVT_0.8.4_small/model/whisper
- 运行方式：cpu
- VAD辅助：True
[2024-07-25 03:16:15.932] [ctranslate2] [thread 4900] [warning] The compute type inferred from the saved model is float16, but the target device or backend do not support efficient float16 computation. The model weights have been automatically converted to use the float32 compute type instead.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<string>", line 1, in <module>
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\idm\AAVT_0.8.4_small\project\utils\utils2.py", line 143, in faster_whisper_result
    segments, _ = model.transcribe(file_path,
  File "D:\idm\AAVT_0.8.4_small\env\lib\site-packages\faster_whisper\transcribe.py", line 333, in transcribe
    speech_chunks = get_speech_timestamps(audio, vad_parameters)
  File "D:\idm\AAVT_0.8.4_small\env\lib\site-packages\faster_whisper\vad.py", line 74, in get_speech_timestamps
    model = get_vad_model()
  File "D:\idm\AAVT_0.8.4_small\env\lib\site-packages\faster_whisper\vad.py", line 229, in get_vad_model
    return SileroVADModel(path)
  File "D:\idm\AAVT_0.8.4_small\env\lib\site-packages\faster_whisper\vad.py", line 235, in __init__
    import onnxruntime
  File "D:\idm\AAVT_0.8.4_small\env\lib\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "D:\idm\AAVT_0.8.4_small\env\lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
AttributeError: _ARRAY_API not found
Process Process-2:
Traceback (most recent call last):
  File "D:\idm\AAVT_0.8.4_small\env\lib\site-packages\faster_whisper\vad.py", line 235, in __init__
    import onnxruntime
  File "D:\idm\AAVT_0.8.4_small\env\lib\site-packages\onnxruntime\__init__.py", line 57, in <module>
    raise import_capi_exception
  File "D:\idm\AAVT_0.8.4_small\env\lib\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "D:\idm\AAVT_0.8.4_small\env\lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
ImportError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\idm\AAVT_0.8.4_small\project\utils\utils2.py", line 143, in faster_whisper_result
    segments, _ = model.transcribe(file_path,
  File "D:\idm\AAVT_0.8.4_small\env\lib\site-packages\faster_whisper\transcribe.py", line 333, in transcribe
    speech_chunks = get_speech_timestamps(audio, vad_parameters)
  File "D:\idm\AAVT_0.8.4_small\env\lib\site-packages\faster_whisper\vad.py", line 74, in get_speech_timestamps
    model = get_vad_model()
  File "D:\idm\AAVT_0.8.4_small\env\lib\site-packages\faster_whisper\vad.py", line 229, in get_vad_model
    return SileroVADModel(path)
  File "D:\idm\AAVT_0.8.4_small\env\lib\site-packages\faster_whisper\vad.py", line 237, in __init__
    raise RuntimeError(
RuntimeError: Applying the VAD filter requires the onnxruntime package
***正在生成SRT字幕文件***

2024-07-25 03:16:17.843 Uncaught app exception
Traceback (most recent call last):
  File "D:\idm\AAVT_0.8.4_small\env\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "D:\idm\AAVT_0.8.4_small\Chenyme-AAVT.py", line 42, in <module>
    media()
  File "D:\idm\AAVT_0.8.4_small\project\media.py", line 457, in media
    srt_content = generate_srt_from_result(result)
  File "D:\idm\AAVT_0.8.4_small\project\utils\utils2.py", line 525, in generate_srt_from_result
    segments = result['segments']
TypeError: 'NoneType' object is not subscriptable

**Comment by chenyme** [comment]
你好，检查一下NumPy库
