### ISSUE TITLE
'docker compose up' doesn't work - Permission denied: '/app/config/font.txt'

### ISSUE THREAD

**Issue by beeender** [Chenyme/Chenyme-AAMT#75]
### 操作系统

linux

### 项目版本

923691c4a716d0c294b2306c7c01dd8bf1b08131

### 错误描述

- `docker compose up`
- Access http://127.0.0.1:8501
- Error page was shown

### 重现步骤

```markdown
❯ docker compose up
[+] Running 2/2
 ✔ Network chenyme-aavt_chenyme-aavt  Created                                                                                                                                         0.0s
 ✔ Container chenyme-aavt             Created                                                                                                                                         0.1s
Attaching to chenyme-aavt
chenyme-aavt  | rsync: [generator] chgrp "/app/config/." failed: Operation not permitted (1)
chenyme-aavt  | rsync: [receiver] mkstemp "/app/config/.audio.toml.d3JqEi" failed: Permission denied (13)
chenyme-aavt  | rsync: [receiver] mkstemp "/app/config/.blog.toml.uKmUCF" failed: Permission denied (13)
chenyme-aavt  | rsync: [receiver] mkstemp "/app/config/.font.txt.37FQbU" failed: Permission denied (13)
chenyme-aavt  | rsync: [receiver] mkstemp "/app/config/.llms.toml.IJYG9p" failed: Permission denied (13)
chenyme-aavt  | rsync: [receiver] mkstemp "/app/config/.project.toml.CNXAMK" failed: Permission denied (13)
chenyme-aavt  | rsync: [receiver] mkstemp "/app/config/.prompt.json.ka5XKq" failed: Permission denied (13)
chenyme-aavt  | rsync: [receiver] mkstemp "/app/config/.translate.toml.jlKMwE" failed: Permission denied (13)
chenyme-aavt  | rsync: [receiver] mkstemp "/app/config/.video.toml.xEIqIB" failed: Permission denied (13)
chenyme-aavt  | rsync: [receiver] mkstemp "/app/config/.whisper.toml.8G9bim" failed: Permission denied (13)
chenyme-aavt  | rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1338) [sender=3.2.7]
chenyme-aavt  | rsync: [generator] chgrp "/app/cache/." failed: Operation not permitted (1)
chenyme-aavt  | rsync: [generator] recv_generator: mkdir "/app/cache/audio" failed: Permission denied (13)
chenyme-aavt  | *** Skipping any contents from this failed directory ***
chenyme-aavt  | rsync: [generator] recv_generator: mkdir "/app/cache/blog" failed: Permission denied (13)
chenyme-aavt  | *** Skipping any contents from this failed directory ***
chenyme-aavt  | rsync: [generator] recv_generator: mkdir "/app/cache/public" failed: Permission denied (13)
chenyme-aavt  | *** Skipping any contents from this failed directory ***
chenyme-aavt  | rsync: [generator] recv_generator: mkdir "/app/cache/translate" failed: Permission denied (13)
chenyme-aavt  | *** Skipping any contents from this failed directory ***
chenyme-aavt  | rsync: [generator] recv_generator: mkdir "/app/cache/tts" failed: Permission denied (13)
chenyme-aavt  | *** Skipping any contents from this failed directory ***
chenyme-aavt  | rsync: [generator] recv_generator: mkdir "/app/cache/video" failed: Permission denied (13)
chenyme-aavt  | *** Skipping any contents from this failed directory ***
chenyme-aavt  | rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1338) [sender=3.2.7]
chenyme-aavt  |
chenyme-aavt  |  █████╗  █████╗ ██╗   ██╗████████╗
chenyme-aavt  | ██╔══██╗██╔══██╗██║   ██║╚══██╔══╝
chenyme-aavt  | ███████║███████║██║   ██║   ██║
chenyme-aavt  | ██╔══██║██╔══██║╚██╗ ██╔╝   ██║
chenyme-aavt  | ██║  ██║██║  ██║ ╚████╔╝    ██║
chenyme-aavt  | ╚═╝  ╚═╝╚═╝  ╚═╝  ╚═══╝     ╚═╝
chenyme-aavt  |
chenyme-aavt  | ╔═╗┬ ┬┌─┐┌┐┌┬ ┬┌┬┐┌─┐
chenyme-aavt  | ║  ├─┤├┤ │││└┬┘│││├┤
chenyme-aavt  | ╚═╝┴ ┴└─┘┘└┘ ┴ ┴ ┴└─┘
chenyme-aavt  |
chenyme-aavt  | 欢迎使用 Chenyme-AAVT V0.9.0!
chenyme-aavt  | 首次使用的登录密码为：chenymeaavt
chenyme-aavt  | 可前往设置中关闭项目保护功能
chenyme-aavt  |
chenyme-aavt  |
chenyme-aavt  |   You can now view your Streamlit app in your browser.
chenyme-aavt  |
chenyme-aavt  |   Local URL: http://localhost:8501
chenyme-aavt  |   Network URL: http://172.18.0.2:8501
chenyme-aavt  |   External URL: http://213.202.218.47:8501
chenyme-aavt  |
chenyme-aavt  | 2024-10-17 13:30:34.821 Uncaught app exception
chenyme-aavt  | Traceback (most recent call last):
chenyme-aavt  |   File "/app/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 85, in exec_func_with_error_handling
chenyme-aavt  |     result = func()
chenyme-aavt  |              ^^^^^^
chenyme-aavt  |   File "/app/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 576, in code_to_exec
chenyme-aavt  |     exec(code, module.__dict__)
chenyme-aavt  |   File "/app/Chenyme-AAVT.py", line 8, in <module>
chenyme-aavt  |     get_font_data()
chenyme-aavt  |   File "/app/utils/get_font.py", line 45, in get_font_data
chenyme-aavt  |     with open(path, 'w', encoding='utf-8') as file:
chenyme-aavt  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chenyme-aavt  | PermissionError: [Errno 13] Permission denied: '/app/config/font.txt'
chenyme-aavt  | 2024-10-17 13:30:55.708 Uncaught app exception
chenyme-aavt  | Traceback (most recent call last):
chenyme-aavt  |   File "/app/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 85, in exec_func_with_error_handling
chenyme-aavt  |     result = func()
chenyme-aavt  |              ^^^^^^
chenyme-aavt  |   File "/app/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 576, in code_to_exec
chenyme-aavt  |     exec(code, module.__dict__)
chenyme-aavt  |   File "/app/Chenyme-AAVT.py", line 8, in <module>
chenyme-aavt  |     get_font_data()
chenyme-aavt  |   File "/app/utils/get_font.py", line 45, in get_font_data
chenyme-aavt  |     with open(path, 'w', encoding='utf-8') as file:
chenyme-aavt  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chenyme-aavt  | PermissionError: [Errno 13] Permission denied: '/app/config/font.txt'
^A[^B^CGracefully stopping... (press Ctrl+C again to force)
[+] Stopping 0/1
[+] Stopping 1/1nyme-aavt  Stopping                                                                                                                        ✔ Container chenyme-aavt  Stopped                                                                                                                  10.2s
canceled
```

```
PermissionError: [Errno 13] Permission denied: '/app/config/font.txt'
Traceback:

File "/app/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
             ^^^^^^
File "/app/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
File "/app/Chenyme-AAVT.py", line 8, in <module>
    get_font_data()
File "/app/utils/get_font.py", line 45, in get_font_data
    with open(path, 'w', encoding='utf-8') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
```


### 错误截图

_No response_

### 其他信息（可选）

_No response_

**Comment by solitudealma** [comment]
sudo启动试试？

**Comment by widewind2015** [comment]
检查 conf 和 output 目录所属的 user id 和 group id 是否都为 1000. 
```
$ ls -n|grep output
drwxr-xr-x 8 1000 1000  4096 Aug 23 12:45 output
```

**Comment by continue33** [comment]
#先获取你的这个容器的id
`docker ps` 项目名称前面那个NAMES就是

# 以 root 身份进入容器，执行权限修改命令：
`docker exec -u root -it 容器ID bash`

# 修改权限
`chmod -R 777 /app/config`

最后
```
docker-compose down
docker-compose up -d
```

理论上你还可以直接以root用户启动docker，但是这个不推荐
```
services:
  your-service:
    user: root
```

**Comment by tooilxui** [comment]
> #先获取你的这个容器的id `docker ps` 项目名称前面那个NAMES就是
> 
> # 以 root 身份进入容器，执行权限修改命令：
> `docker exec -u root -it 容器ID bash`
> 
> # 修改权限
> `chmod -R 777 /app/config`
> 
> 最后
> 
> ```
> docker-compose down
> docker-compose up -d
> ```
> 
> 理论上你还可以直接以root用户启动docker，但是这个不推荐
> 
> ```
> services:
>   your-service:
>     user: root
> ```

哥你救了我！受小弟一拜！
