### ISSUE TITLE
【错误】0.6.1测试发现的Bug

### ISSUE THREAD

**Issue by blackwhites** [Chenyme/Chenyme-AAMT#9]
转audio的时候报错，转video没有报错
<img width="1427" alt="2024-03-12_22-30-46" src="https://github.com/Chenyme/Chenyme-AAVT/assets/5109753/8d892188-15f6-4e8d-bb93-5d37e18d5ce5">

 File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "C:\Chenyme_AAVT_0.6.1\pages\🎙️音频(Audio).py", line 46, in <module>
    result = get_whisper_result(uploaded_file, cache_dir, device, w_model_option, w_version, vad)
TypeError: get_whisper_result() missing 3 required positional arguments: 'lang', 'beam_size', and 'min_vad'
2024-03-12 07:30:23.183 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "C:\Chenyme_AAVT_0.6.1\pages\🎙️音频(Audio).py", line 46, in <module>
    result = get_whisper_result(uploaded_file, cache_dir, device, w_model_option, w_version, vad)
TypeError: get_whisper_result() missing 3 required positional arguments: 'lang', 'beam_size', and 'min_vad'

**Comment by chenyme** [comment]
你好！谢谢你的反馈，现已发布修复版本`V0.6.1_Fixbug`，您可以重新下载并正常使用~再次感谢你的反馈！
版本链接：[V0.6.1_Fixbug](https://github.com/Chenyme/Chenyme-AAVT/releases/tag/V0.6.1_Fixbug)
